# Bayes++ rtheta Makefile
# Range Angle test for all filter schemse
#

# Modify these settings to locate Boost and bjam
BJAM = bjam

GOBJAM = $(BJAM) $(ARGS)

# Build everything
buildRtheta:
	$(GOBJAM)
